<?php

declare(strict_types=1);

use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Route;

/**
 * item/openapi-reference (issue #25), doneWhen: "Adding an unlisted route
 * fails the contract test, mutation-checked; openapi.json is committed."
 *
 * Two directions, both read through the router -- Route::getRoutes(), the
 * same source tests/Feature/Api/RouteSurfaceTest.php reads, never
 * routes/api.php's own text (its function below applies that file's own
 * verbatim) -- against docs/api/openapi.json as committed, never
 * regenerated by this test:
 *
 *   - every route registered under api.v1.* has a matching path+method in
 *     the document (a route added and never documented fails HERE -- this
 *     is the doneWhen clause);
 *   - every path+method in the document maps to a route actually registered
 *     (the document cannot rot into describing an endpoint that no longer
 *     exists, the same drift App\Console\Commands\GenerateOpenApi's own
 *     --check guards when a developer remembers to run it).
 *
 * HEAD is dropped from the "live" side before comparing: Laravel registers
 * it automatically alongside every GET on the SAME route object, and the
 * document -- like most hand-read OpenAPI references -- does not list it as
 * a second operation. Comparing it unfiltered would fail every GET route
 * for a reason that has nothing to do with an undocumented endpoint.
 */
function openApiV1Routes(): Collection
{
    // The same filter RouteSurfaceTest.php's own apiV1Routes() applies --
    // see that file's docblock for why 'api/v1/', not 'v1/', is the URI
    // that matches what actually got REGISTERED.
    //
    // Deliberately NOT named apiV1Routes(). Pest loads every test file into
    // one PHP process, so a second file declaring that name is a fatal
    // "Cannot redeclare" that takes the WHOLE suite down, not just this
    // file -- which is why no two helpers anywhere in tests/ share a name.
    return collect(Route::getRoutes())->filter(
        fn (Illuminate\Routing\Route $route): bool => str_starts_with($route->uri(), 'api/v1/'),
    );
}

/** @return Collection<int, string> "METHOD /path" pairs, HEAD dropped, path relative to /api/v1. */
function liveRouteSet(): Collection
{
    return openApiV1Routes()->flatMap(function (Illuminate\Routing\Route $route): array {
        $path = '/'.preg_replace('#^api/v1/?#', '', $route->uri());

        return collect($route->methods())
            ->reject(fn (string $method): bool => $method === 'HEAD')
            ->map(fn (string $method): string => "{$method} {$path}")
            ->all();
    })->values();
}

/** @return Collection<int, string> "METHOD /path" pairs from the committed document. */
function documentedRouteSet(): Collection
{
    $document = json_decode(
        file_get_contents(base_path('docs/api/openapi.json')),
        associative: true,
        flags: JSON_THROW_ON_ERROR,
    );

    $set = [];

    foreach ($document['paths'] ?? [] as $path => $operations) {
        foreach (array_keys($operations) as $method) {
            $set[] = strtoupper($method).' '.$path;
        }
    }

    return collect($set);
}

it('commits a non-empty openapi.json describing the real route surface', function () {
    // Same non-vacuity guard as RouteSurfaceTest's own first test: an empty
    // document would make every assertion below true for the wrong reason.
    expect(liveRouteSet()->count())->toBeGreaterThanOrEqual(15)
        ->and(documentedRouteSet()->count())->toBeGreaterThanOrEqual(15);
});

it('documents every registered api.v1 route', function () {
    $undocumented = liveRouteSet()->diff(documentedRouteSet());

    expect($undocumented->all())->toBe([]);
});

it('never documents a route that no longer exists', function () {
    $phantom = documentedRouteSet()->diff(liveRouteSet());

    expect($phantom->all())->toBe([]);
});

/**
 * The mutation-proof half of "documents every registered api.v1 route":
 * register one extra api.v1.* route the committed document cannot possibly
 * list, and confirm the FIRST assertion above -- run again, by hand, against
 * the now-mutated live set -- actually catches it. Without this, "adding an
 * unlisted route fails the contract test" (this item's own doneWhen clause)
 * would be a claim nobody had checked, exactly what CLAUDE.md's testing
 * section warns a citation of evidence must not be.
 */
it('fails the undocumented-route check when one is actually added', function () {
    Route::get('api/v1/__mutation-probe/openapi', fn () => null)
        ->name('api.v1.__mutation-probe.openapi-probe');

    $undocumented = liveRouteSet()->diff(documentedRouteSet());

    expect($undocumented->all())->not->toBe([])
        ->and($undocumented->contains('GET /__mutation-probe/openapi'))->toBeTrue();
});
